namespace DemLock.Parser.Models;

/// <summary>
/// Enum containing the mapping for ints to the message type so that
/// parsed messages can be properly mapped to the handler function
/// </summary>
public enum MessageTypes
{
    // ReSharper disable InconsistentNaming


    net_Tick = 4,
    net_SetConVar = 6,
    net_SignonState = 7,
    net_SpawnGroup_Load = 8,
    net_SpawnGroup_SetCreationTick = 11,
    
    svc_ServerInfo = 40,
    svc_ClassInfo = 42,
    svc_CreateStringTable = 44,
    svc_UpdateStringTable = 45,
    svc_VoiceInit = 46,
    svc_ClearAllStringTables = 51,
    svc_PacketEntities = 55,
    svc_HLTVStatus = 62,

	UM_ParticleManager = 145,
	UM_PlayResponseConditional = 166,

    GE_Source1LegacyGameEventList = 205,
    GE_Source1LegacyGameEvent = 207,
    GE_SosStartSoundEvent = 208,
    GE_SosStopSoundEvent = 209,
    GE_SosSetSoundEventParams = 210,
    GE_SosStopSoundEventHash = 212,
    GE_FireBullets = 450,
    GE_PlayerAnimEvent = 451,
    GE_ParticleSystemManager = 458,
    GE_ScreenTextPretty = 459,
    GE_ServerRequestedTracer = 460,
    GE_BulletImpact = 461,
    GE_EnableSatVolumesEvent = 462,
    GE_PlaceSatVolumeEvent = 463,
    GE_DisableSatVolumesEvent = 464,
    GE_RemoveSatVolumeEvent = 465,
    
    k_EUserMsg_Damage = 300,
    k_EUserMsg_MapPing = 303,
    k_EUserMsg_TeamRewards = 304,
    k_EUserMsg_AbilityFailed = 306,
    k_EUserMsg_TriggerDamageFlash = 308,
    k_EUserMsg_AbilitiesChanged = 309,
    k_EUserMsg_RecentDamageSummary = 310,
    k_EUserMsg_SpectatorTeamChanged = 311,
    k_EUserMsg_ChatWheel = 312,
    k_EUserMsg_GoldHistory = 313,
    k_EUserMsg_ChatMsg = 314,
    k_EUserMsg_QuickResponse = 315,
    k_EUserMsg_PostMatchDetails = 316,
    k_EUserMsg_ChatEvent = 317,
    k_EUserMsg_AbilityInterrupted = 318,
    k_EUserMsg_HeroKilled = 319,
    k_EUserMsg_ReturnIdol = 320,
    k_EUserMsg_SetClientCameraAngles = 321,
    k_EUserMsg_MapLine = 322,
    k_EUserMsg_BulletHit = 323,
    k_EUserMsg_ObjectiveMask = 324,
    k_EUserMsg_ModifierApplied = 325,
    k_EUserMsg_CameraController = 326,
    k_EUserMsg_AuraModifierApplied = 327,
    k_EUserMsg_ObstructedShotFired = 329,
    k_EUserMsg_AbilityLateFailure = 330,
    k_EUserMsg_AbilityPing = 331,
    k_EUserMsg_PostProcessingAnim = 332,
    k_EUserMsg_DeathReplayData = 333,
    k_EUserMsg_PlayerLifetimeStatInfo = 334,
    k_EUserMsg_ForceShopClosed = 336,
    k_EUserMsg_StaminaDrained = 337,
    k_EUserMsg_AbilityNotify = 338,
    k_EUserMsg_GetDamageStatsResponse = 339,
    k_EUserMsg_ParticipantStartSoundEvent = 340,
    k_EUserMsg_ParticipantStopSoundEvent = 341,
    k_EUserMsg_ParticipantStopSoundEventHash = 342,
    k_EUserMsg_ParticipantSetSoundEventParams = 343,
    k_EUserMsg_ParticipantSetLibraryStackFields = 344,
    k_EUserMsg_CurrencyChanged = 345,
    k_EUserMsg_GameOver = 346,
    k_EUserMsg_BossKilled = 347,
	k_EEntityMsg_BreakablePropSpawnDebris = 500,
	
    TE_EffectDispatchId = 400,
    TE_ArmorRicochetId = 401,
    TE_BeamEntPointId = 402,
    TE_BeamEntsId = 403,
    TE_BeamPointsId = 404,
    TE_BeamRingId = 405,
    TE_BSPDecalId = 407,
    TE_BubblesId = 408,
    TE_BubbleTrailId = 409,
    TE_DecalId = 410,
    TE_WorldDecalId = 411,
    TE_EnergySplashId = 412,
    TE_FizzId = 413,
    TE_ShatterSurfaceId = 414,
    TE_GlowSpriteId = 415,
    TE_ImpactId = 416,
    TE_MuzzleFlashId = 417,
    TE_BloodStreamId = 418,
    TE_ExplosionId = 419,
    TE_DustId = 420,
    TE_LargeFunnelId = 421,
    TE_SparksId = 422,
    TE_PhysicsPropId = 423,
    TE_PlayerDecalId = 424,
    TE_ProjectedDecalId = 425,
    TE_SmokeId = 426,

    // ReSharper enable InconsistentNaming
}
