// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: citadel_gamemessages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from citadel_gamemessages.proto</summary>
public static partial class CitadelGamemessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for citadel_gamemessages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CitadelGamemessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChpjaXRhZGVsX2dhbWVtZXNzYWdlcy5wcm90byKwAQoWQ01zZ0NsaWVudFNl",
          "cnZlckhlYWRlchIYChBnYW1lX2luc3RhbmNlX2lkGAEgASgEEhoKEmxvY2Fs",
          "X3BsYXllcl9pbmRleBgCIAEoDRIPCgdwYXlsb2FkGAMgASgMEk8KBm1zZ19p",
          "ZBgEIAEoDjIVLkVDaXRhZGVsR2FtZU1lc3NhZ2VzOihrX0VNc2dHYW1lU2Vy",
          "dmVyVG9DbGllbnRDb25uZWN0aW9uU3RhdHVzIiUKI0NNc2dHYW1lU2VydmVy",
          "VG9DbGllbnRHYW1lQ29tcGxldGVkIh8KHUNNc2dHYW1lU2VydmVyVG9DbGll",
          "bnRHb29kYnllIvECCiZDTXNnR2FtZVNlcnZlclRvQ2xpZW50Q29ubmVjdGlv",
          "blN0YXR1cxI/CgdwbGF5ZXJzGAEgAygLMi4uQ01zZ0dhbWVTZXJ2ZXJUb0Ns",
          "aWVudENvbm5lY3Rpb25TdGF0dXMuUGxheWVyGtMBCgZQbGF5ZXISFwoLcGxh",
          "eWVyX3Nsb3QYASABKAU6Ai0xEk0KBnN0YXR1cxgCIAEoDjIvLkNNc2dHYW1l",
          "U2VydmVyVG9DbGllbnRDb25uZWN0aW9uU3RhdHVzLkVTdGF0dXM6DGtfRUNv",
          "bm5lY3RlZBIaChJpbmFjdGl2aXR5X3RpY2tpbmcYAyABKAgSHwoXaW5hY3Rp",
          "dml0eV9tc19yZW1haW5pbmcYBCABKA0SJAocaW5hY3Rpdml0eV9hbmltX21z",
          "X3JlbWFpbmluZxgFIAEoDSIwCgdFU3RhdHVzEhAKDGtfRUNvbm5lY3RlZBAB",
          "EhMKD2tfRURpc2Nvbm5lY3RlZBACIqgBChRDQ2xpZW50UmVjb25uZWN0SW5m",
          "bxIXCg9zZXJ2ZXJfc3RlYW1faWQYASABKAYSEAoIbG9iYnlfaWQYAiABKAQS",
          "FAoMdGltZV91cGRhdGVkGAMgASgNEhYKDnVkcF9jb25uZWN0X2lwGAQgASgN",
          "EhgKEHVkcF9jb25uZWN0X3BvcnQYBSABKA0SHQoVY29tcGF0aWJpbGl0eV92",
          "ZXJzaW9uGAYgASgNIlAKIENNc2dDbGllbnRBY2NvdW50U3luY1N0b3JhZ2VG",
          "aWxlEg8KB3ZlcnNpb24YASABKA0SCwoDaWRzGAIgAygNEg4KBnZhbHVlcxgD",
          "IAMoDSrCAQoURUNpdGFkZWxHYW1lTWVzc2FnZXMSLAooa19FTXNnR2FtZVNl",
          "cnZlclRvQ2xpZW50Q29ubmVjdGlvblN0YXR1cxAKEiwKKGtfRU1zZ0dhbWVT",
          "ZXJ2ZXJUb0NsaWVudEluaXRpYWxHYW1lU3RhdGUQDBIpCiVrX0VNc2dHYW1l",
          "U2VydmVyVG9DbGllbnRHYW1lQ29tcGxldGVkEA0SIwofa19FTXNnR2FtZVNl",
          "cnZlclRvQ2xpZW50R29vZGJ5ZRAPKssDChhFQ2l0YWRlbERpc2Nvbm5lY3RS",
          "ZWFzb24SLgopa19FQ2l0YWRlbERpc2Nvbm5lY3RSZWFzb25fVXNlckxlYXZl",
          "TWF0Y2gQ6QcSKwoma19FQ2l0YWRlbERpc2Nvbm5lY3RSZWFzb25fVXNlclF1",
          "aXRBcHAQ6gcSKgola19FQ2l0YWRlbERpc2Nvbm5lY3RSZWFzb25fVXNlckNh",
          "bmNlbBDrBxInCiJrX0VDaXRhZGVsRGlzY29ubmVjdFJlYXNvbl9Hb29kYnll",
          "EOwHEioKJWtfRUNpdGFkZWxEaXNjb25uZWN0UmVhc29uX0JhZE1lc3NhZ2UQ",
          "0Q8SOQo0a19FQ2l0YWRlbERpc2Nvbm5lY3RSZWFzb25fR2FtZURlc3Ryb3ll",
          "ZFVuZXhwZWN0ZWRseRDSDxIuCilrX0VDaXRhZGVsRGlzY29ubmVjdFJlYXNv",
          "bl9DaGFuZ2luZ1NlcnZlchDTDxItCihrX0VDaXRhZGVsRGlzY29ubmVjdFJl",
          "YXNvbl9PbGRDb25uZWN0aW9uENQPEjcKMmtfRUNpdGFkZWxEaXNjb25uZWN0",
          "UmVhc29uX0dvb2RieWVVbnJlY29nbml6ZWRHYW1lENUP"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ECitadelGameMessages), typeof(global::ECitadelDisconnectReason), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::CMsgClientServerHeader), global::CMsgClientServerHeader.Parser, new[]{ "GameInstanceId", "LocalPlayerIndex", "Payload", "MsgId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CMsgGameServerToClientGameCompleted), global::CMsgGameServerToClientGameCompleted.Parser, null, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CMsgGameServerToClientGoodbye), global::CMsgGameServerToClientGoodbye.Parser, null, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CMsgGameServerToClientConnectionStatus), global::CMsgGameServerToClientConnectionStatus.Parser, new[]{ "Players" }, null, new[]{ typeof(global::CMsgGameServerToClientConnectionStatus.Types.EStatus) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::CMsgGameServerToClientConnectionStatus.Types.Player), global::CMsgGameServerToClientConnectionStatus.Types.Player.Parser, new[]{ "PlayerSlot", "Status", "InactivityTicking", "InactivityMsRemaining", "InactivityAnimMsRemaining" }, null, null, null, null)}),
          new pbr::GeneratedClrTypeInfo(typeof(global::CClientReconnectInfo), global::CClientReconnectInfo.Parser, new[]{ "ServerSteamId", "LobbyId", "TimeUpdated", "UdpConnectIp", "UdpConnectPort", "CompatibilityVersion" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CMsgClientAccountSyncStorageFile), global::CMsgClientAccountSyncStorageFile.Parser, new[]{ "Version", "Ids", "Values" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum ECitadelGameMessages {
  [pbr::OriginalName("k_EMsgGameServerToClientConnectionStatus")] KEmsgGameServerToClientConnectionStatus = 10,
  [pbr::OriginalName("k_EMsgGameServerToClientInitialGameState")] KEmsgGameServerToClientInitialGameState = 12,
  [pbr::OriginalName("k_EMsgGameServerToClientGameCompleted")] KEmsgGameServerToClientGameCompleted = 13,
  [pbr::OriginalName("k_EMsgGameServerToClientGoodbye")] KEmsgGameServerToClientGoodbye = 15,
}

public enum ECitadelDisconnectReason {
  [pbr::OriginalName("k_ECitadelDisconnectReason_UserLeaveMatch")] KEcitadelDisconnectReasonUserLeaveMatch = 1001,
  [pbr::OriginalName("k_ECitadelDisconnectReason_UserQuitApp")] KEcitadelDisconnectReasonUserQuitApp = 1002,
  [pbr::OriginalName("k_ECitadelDisconnectReason_UserCancel")] KEcitadelDisconnectReasonUserCancel = 1003,
  [pbr::OriginalName("k_ECitadelDisconnectReason_Goodbye")] KEcitadelDisconnectReasonGoodbye = 1004,
  [pbr::OriginalName("k_ECitadelDisconnectReason_BadMessage")] KEcitadelDisconnectReasonBadMessage = 2001,
  [pbr::OriginalName("k_ECitadelDisconnectReason_GameDestroyedUnexpectedly")] KEcitadelDisconnectReasonGameDestroyedUnexpectedly = 2002,
  [pbr::OriginalName("k_ECitadelDisconnectReason_ChangingServer")] KEcitadelDisconnectReasonChangingServer = 2003,
  [pbr::OriginalName("k_ECitadelDisconnectReason_OldConnection")] KEcitadelDisconnectReasonOldConnection = 2004,
  [pbr::OriginalName("k_ECitadelDisconnectReason_GoodbyeUnrecognizedGame")] KEcitadelDisconnectReasonGoodbyeUnrecognizedGame = 2005,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class CMsgClientServerHeader : pb::IMessage<CMsgClientServerHeader>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CMsgClientServerHeader> _parser = new pb::MessageParser<CMsgClientServerHeader>(() => new CMsgClientServerHeader());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CMsgClientServerHeader> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CitadelGamemessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientServerHeader() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientServerHeader(CMsgClientServerHeader other) : this() {
    _hasBits0 = other._hasBits0;
    gameInstanceId_ = other.gameInstanceId_;
    localPlayerIndex_ = other.localPlayerIndex_;
    payload_ = other.payload_;
    msgId_ = other.msgId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientServerHeader Clone() {
    return new CMsgClientServerHeader(this);
  }

  /// <summary>Field number for the "game_instance_id" field.</summary>
  public const int GameInstanceIdFieldNumber = 1;
  private readonly static ulong GameInstanceIdDefaultValue = 0UL;

  private ulong gameInstanceId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong GameInstanceId {
    get { if ((_hasBits0 & 1) != 0) { return gameInstanceId_; } else { return GameInstanceIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      gameInstanceId_ = value;
    }
  }
  /// <summary>Gets whether the "game_instance_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasGameInstanceId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "game_instance_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearGameInstanceId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "local_player_index" field.</summary>
  public const int LocalPlayerIndexFieldNumber = 2;
  private readonly static uint LocalPlayerIndexDefaultValue = 0;

  private uint localPlayerIndex_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint LocalPlayerIndex {
    get { if ((_hasBits0 & 2) != 0) { return localPlayerIndex_; } else { return LocalPlayerIndexDefaultValue; } }
    set {
      _hasBits0 |= 2;
      localPlayerIndex_ = value;
    }
  }
  /// <summary>Gets whether the "local_player_index" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasLocalPlayerIndex {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "local_player_index" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearLocalPlayerIndex() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "payload" field.</summary>
  public const int PayloadFieldNumber = 3;
  private readonly static pb::ByteString PayloadDefaultValue = pb::ByteString.Empty;

  private pb::ByteString payload_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Payload {
    get { return payload_ ?? PayloadDefaultValue; }
    set {
      payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "payload" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasPayload {
    get { return payload_ != null; }
  }
  /// <summary>Clears the value of the "payload" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPayload() {
    payload_ = null;
  }

  /// <summary>Field number for the "msg_id" field.</summary>
  public const int MsgIdFieldNumber = 4;
  private readonly static global::ECitadelGameMessages MsgIdDefaultValue = global::ECitadelGameMessages.KEmsgGameServerToClientConnectionStatus;

  private global::ECitadelGameMessages msgId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ECitadelGameMessages MsgId {
    get { if ((_hasBits0 & 4) != 0) { return msgId_; } else { return MsgIdDefaultValue; } }
    set {
      _hasBits0 |= 4;
      msgId_ = value;
    }
  }
  /// <summary>Gets whether the "msg_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasMsgId {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "msg_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMsgId() {
    _hasBits0 &= ~4;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CMsgClientServerHeader);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CMsgClientServerHeader other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (GameInstanceId != other.GameInstanceId) return false;
    if (LocalPlayerIndex != other.LocalPlayerIndex) return false;
    if (Payload != other.Payload) return false;
    if (MsgId != other.MsgId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasGameInstanceId) hash ^= GameInstanceId.GetHashCode();
    if (HasLocalPlayerIndex) hash ^= LocalPlayerIndex.GetHashCode();
    if (HasPayload) hash ^= Payload.GetHashCode();
    if (HasMsgId) hash ^= MsgId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasGameInstanceId) {
      output.WriteRawTag(8);
      output.WriteUInt64(GameInstanceId);
    }
    if (HasLocalPlayerIndex) {
      output.WriteRawTag(16);
      output.WriteUInt32(LocalPlayerIndex);
    }
    if (HasPayload) {
      output.WriteRawTag(26);
      output.WriteBytes(Payload);
    }
    if (HasMsgId) {
      output.WriteRawTag(32);
      output.WriteEnum((int) MsgId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasGameInstanceId) {
      output.WriteRawTag(8);
      output.WriteUInt64(GameInstanceId);
    }
    if (HasLocalPlayerIndex) {
      output.WriteRawTag(16);
      output.WriteUInt32(LocalPlayerIndex);
    }
    if (HasPayload) {
      output.WriteRawTag(26);
      output.WriteBytes(Payload);
    }
    if (HasMsgId) {
      output.WriteRawTag(32);
      output.WriteEnum((int) MsgId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasGameInstanceId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GameInstanceId);
    }
    if (HasLocalPlayerIndex) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LocalPlayerIndex);
    }
    if (HasPayload) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
    }
    if (HasMsgId) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CMsgClientServerHeader other) {
    if (other == null) {
      return;
    }
    if (other.HasGameInstanceId) {
      GameInstanceId = other.GameInstanceId;
    }
    if (other.HasLocalPlayerIndex) {
      LocalPlayerIndex = other.LocalPlayerIndex;
    }
    if (other.HasPayload) {
      Payload = other.Payload;
    }
    if (other.HasMsgId) {
      MsgId = other.MsgId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          GameInstanceId = input.ReadUInt64();
          break;
        }
        case 16: {
          LocalPlayerIndex = input.ReadUInt32();
          break;
        }
        case 26: {
          Payload = input.ReadBytes();
          break;
        }
        case 32: {
          MsgId = (global::ECitadelGameMessages) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          GameInstanceId = input.ReadUInt64();
          break;
        }
        case 16: {
          LocalPlayerIndex = input.ReadUInt32();
          break;
        }
        case 26: {
          Payload = input.ReadBytes();
          break;
        }
        case 32: {
          MsgId = (global::ECitadelGameMessages) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class CMsgGameServerToClientGameCompleted : pb::IMessage<CMsgGameServerToClientGameCompleted>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CMsgGameServerToClientGameCompleted> _parser = new pb::MessageParser<CMsgGameServerToClientGameCompleted>(() => new CMsgGameServerToClientGameCompleted());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CMsgGameServerToClientGameCompleted> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CitadelGamemessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgGameServerToClientGameCompleted() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgGameServerToClientGameCompleted(CMsgGameServerToClientGameCompleted other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgGameServerToClientGameCompleted Clone() {
    return new CMsgGameServerToClientGameCompleted(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CMsgGameServerToClientGameCompleted);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CMsgGameServerToClientGameCompleted other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CMsgGameServerToClientGameCompleted other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class CMsgGameServerToClientGoodbye : pb::IMessage<CMsgGameServerToClientGoodbye>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CMsgGameServerToClientGoodbye> _parser = new pb::MessageParser<CMsgGameServerToClientGoodbye>(() => new CMsgGameServerToClientGoodbye());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CMsgGameServerToClientGoodbye> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CitadelGamemessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgGameServerToClientGoodbye() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgGameServerToClientGoodbye(CMsgGameServerToClientGoodbye other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgGameServerToClientGoodbye Clone() {
    return new CMsgGameServerToClientGoodbye(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CMsgGameServerToClientGoodbye);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CMsgGameServerToClientGoodbye other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CMsgGameServerToClientGoodbye other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class CMsgGameServerToClientConnectionStatus : pb::IMessage<CMsgGameServerToClientConnectionStatus>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CMsgGameServerToClientConnectionStatus> _parser = new pb::MessageParser<CMsgGameServerToClientConnectionStatus>(() => new CMsgGameServerToClientConnectionStatus());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CMsgGameServerToClientConnectionStatus> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CitadelGamemessagesReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgGameServerToClientConnectionStatus() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgGameServerToClientConnectionStatus(CMsgGameServerToClientConnectionStatus other) : this() {
    players_ = other.players_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgGameServerToClientConnectionStatus Clone() {
    return new CMsgGameServerToClientConnectionStatus(this);
  }

  /// <summary>Field number for the "players" field.</summary>
  public const int PlayersFieldNumber = 1;
  private static readonly pb::FieldCodec<global::CMsgGameServerToClientConnectionStatus.Types.Player> _repeated_players_codec
      = pb::FieldCodec.ForMessage(10, global::CMsgGameServerToClientConnectionStatus.Types.Player.Parser);
  private readonly pbc::RepeatedField<global::CMsgGameServerToClientConnectionStatus.Types.Player> players_ = new pbc::RepeatedField<global::CMsgGameServerToClientConnectionStatus.Types.Player>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::CMsgGameServerToClientConnectionStatus.Types.Player> Players {
    get { return players_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CMsgGameServerToClientConnectionStatus);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CMsgGameServerToClientConnectionStatus other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!players_.Equals(other.players_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= players_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    players_.WriteTo(output, _repeated_players_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    players_.WriteTo(ref output, _repeated_players_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += players_.CalculateSize(_repeated_players_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CMsgGameServerToClientConnectionStatus other) {
    if (other == null) {
      return;
    }
    players_.Add(other.players_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          players_.AddEntriesFrom(input, _repeated_players_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          players_.AddEntriesFrom(ref input, _repeated_players_codec);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the CMsgGameServerToClientConnectionStatus message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum EStatus {
      [pbr::OriginalName("k_EConnected")] KEconnected = 1,
      [pbr::OriginalName("k_EDisconnected")] KEdisconnected = 2,
    }

    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class Player : pb::IMessage<Player>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<Player> _parser = new pb::MessageParser<Player>(() => new Player());
      private pb::UnknownFieldSet _unknownFields;
      private int _hasBits0;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<Player> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::CMsgGameServerToClientConnectionStatus.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public Player() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public Player(Player other) : this() {
        _hasBits0 = other._hasBits0;
        playerSlot_ = other.playerSlot_;
        status_ = other.status_;
        inactivityTicking_ = other.inactivityTicking_;
        inactivityMsRemaining_ = other.inactivityMsRemaining_;
        inactivityAnimMsRemaining_ = other.inactivityAnimMsRemaining_;
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public Player Clone() {
        return new Player(this);
      }

      /// <summary>Field number for the "player_slot" field.</summary>
      public const int PlayerSlotFieldNumber = 1;
      private readonly static int PlayerSlotDefaultValue = -1;

      private int playerSlot_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int PlayerSlot {
        get { if ((_hasBits0 & 1) != 0) { return playerSlot_; } else { return PlayerSlotDefaultValue; } }
        set {
          _hasBits0 |= 1;
          playerSlot_ = value;
        }
      }
      /// <summary>Gets whether the "player_slot" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasPlayerSlot {
        get { return (_hasBits0 & 1) != 0; }
      }
      /// <summary>Clears the value of the "player_slot" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearPlayerSlot() {
        _hasBits0 &= ~1;
      }

      /// <summary>Field number for the "status" field.</summary>
      public const int StatusFieldNumber = 2;
      private readonly static global::CMsgGameServerToClientConnectionStatus.Types.EStatus StatusDefaultValue = global::CMsgGameServerToClientConnectionStatus.Types.EStatus.KEconnected;

      private global::CMsgGameServerToClientConnectionStatus.Types.EStatus status_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::CMsgGameServerToClientConnectionStatus.Types.EStatus Status {
        get { if ((_hasBits0 & 2) != 0) { return status_; } else { return StatusDefaultValue; } }
        set {
          _hasBits0 |= 2;
          status_ = value;
        }
      }
      /// <summary>Gets whether the "status" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasStatus {
        get { return (_hasBits0 & 2) != 0; }
      }
      /// <summary>Clears the value of the "status" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearStatus() {
        _hasBits0 &= ~2;
      }

      /// <summary>Field number for the "inactivity_ticking" field.</summary>
      public const int InactivityTickingFieldNumber = 3;
      private readonly static bool InactivityTickingDefaultValue = false;

      private bool inactivityTicking_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool InactivityTicking {
        get { if ((_hasBits0 & 4) != 0) { return inactivityTicking_; } else { return InactivityTickingDefaultValue; } }
        set {
          _hasBits0 |= 4;
          inactivityTicking_ = value;
        }
      }
      /// <summary>Gets whether the "inactivity_ticking" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasInactivityTicking {
        get { return (_hasBits0 & 4) != 0; }
      }
      /// <summary>Clears the value of the "inactivity_ticking" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearInactivityTicking() {
        _hasBits0 &= ~4;
      }

      /// <summary>Field number for the "inactivity_ms_remaining" field.</summary>
      public const int InactivityMsRemainingFieldNumber = 4;
      private readonly static uint InactivityMsRemainingDefaultValue = 0;

      private uint inactivityMsRemaining_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint InactivityMsRemaining {
        get { if ((_hasBits0 & 8) != 0) { return inactivityMsRemaining_; } else { return InactivityMsRemainingDefaultValue; } }
        set {
          _hasBits0 |= 8;
          inactivityMsRemaining_ = value;
        }
      }
      /// <summary>Gets whether the "inactivity_ms_remaining" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasInactivityMsRemaining {
        get { return (_hasBits0 & 8) != 0; }
      }
      /// <summary>Clears the value of the "inactivity_ms_remaining" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearInactivityMsRemaining() {
        _hasBits0 &= ~8;
      }

      /// <summary>Field number for the "inactivity_anim_ms_remaining" field.</summary>
      public const int InactivityAnimMsRemainingFieldNumber = 5;
      private readonly static uint InactivityAnimMsRemainingDefaultValue = 0;

      private uint inactivityAnimMsRemaining_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint InactivityAnimMsRemaining {
        get { if ((_hasBits0 & 16) != 0) { return inactivityAnimMsRemaining_; } else { return InactivityAnimMsRemainingDefaultValue; } }
        set {
          _hasBits0 |= 16;
          inactivityAnimMsRemaining_ = value;
        }
      }
      /// <summary>Gets whether the "inactivity_anim_ms_remaining" field is set</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool HasInactivityAnimMsRemaining {
        get { return (_hasBits0 & 16) != 0; }
      }
      /// <summary>Clears the value of the "inactivity_anim_ms_remaining" field</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void ClearInactivityAnimMsRemaining() {
        _hasBits0 &= ~16;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as Player);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(Player other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (PlayerSlot != other.PlayerSlot) return false;
        if (Status != other.Status) return false;
        if (InactivityTicking != other.InactivityTicking) return false;
        if (InactivityMsRemaining != other.InactivityMsRemaining) return false;
        if (InactivityAnimMsRemaining != other.InactivityAnimMsRemaining) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (HasPlayerSlot) hash ^= PlayerSlot.GetHashCode();
        if (HasStatus) hash ^= Status.GetHashCode();
        if (HasInactivityTicking) hash ^= InactivityTicking.GetHashCode();
        if (HasInactivityMsRemaining) hash ^= InactivityMsRemaining.GetHashCode();
        if (HasInactivityAnimMsRemaining) hash ^= InactivityAnimMsRemaining.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (HasPlayerSlot) {
          output.WriteRawTag(8);
          output.WriteInt32(PlayerSlot);
        }
        if (HasStatus) {
          output.WriteRawTag(16);
          output.WriteEnum((int) Status);
        }
        if (HasInactivityTicking) {
          output.WriteRawTag(24);
          output.WriteBool(InactivityTicking);
        }
        if (HasInactivityMsRemaining) {
          output.WriteRawTag(32);
          output.WriteUInt32(InactivityMsRemaining);
        }
        if (HasInactivityAnimMsRemaining) {
          output.WriteRawTag(40);
          output.WriteUInt32(InactivityAnimMsRemaining);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (HasPlayerSlot) {
          output.WriteRawTag(8);
          output.WriteInt32(PlayerSlot);
        }
        if (HasStatus) {
          output.WriteRawTag(16);
          output.WriteEnum((int) Status);
        }
        if (HasInactivityTicking) {
          output.WriteRawTag(24);
          output.WriteBool(InactivityTicking);
        }
        if (HasInactivityMsRemaining) {
          output.WriteRawTag(32);
          output.WriteUInt32(InactivityMsRemaining);
        }
        if (HasInactivityAnimMsRemaining) {
          output.WriteRawTag(40);
          output.WriteUInt32(InactivityAnimMsRemaining);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (HasPlayerSlot) {
          size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerSlot);
        }
        if (HasStatus) {
          size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
        }
        if (HasInactivityTicking) {
          size += 1 + 1;
        }
        if (HasInactivityMsRemaining) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InactivityMsRemaining);
        }
        if (HasInactivityAnimMsRemaining) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InactivityAnimMsRemaining);
        }
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(Player other) {
        if (other == null) {
          return;
        }
        if (other.HasPlayerSlot) {
          PlayerSlot = other.PlayerSlot;
        }
        if (other.HasStatus) {
          Status = other.Status;
        }
        if (other.HasInactivityTicking) {
          InactivityTicking = other.InactivityTicking;
        }
        if (other.HasInactivityMsRemaining) {
          InactivityMsRemaining = other.InactivityMsRemaining;
        }
        if (other.HasInactivityAnimMsRemaining) {
          InactivityAnimMsRemaining = other.InactivityAnimMsRemaining;
        }
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 8: {
              PlayerSlot = input.ReadInt32();
              break;
            }
            case 16: {
              Status = (global::CMsgGameServerToClientConnectionStatus.Types.EStatus) input.ReadEnum();
              break;
            }
            case 24: {
              InactivityTicking = input.ReadBool();
              break;
            }
            case 32: {
              InactivityMsRemaining = input.ReadUInt32();
              break;
            }
            case 40: {
              InactivityAnimMsRemaining = input.ReadUInt32();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
        if ((tag & 7) == 4) {
          // Abort on any end group tag.
          return;
        }
        switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 8: {
              PlayerSlot = input.ReadInt32();
              break;
            }
            case 16: {
              Status = (global::CMsgGameServerToClientConnectionStatus.Types.EStatus) input.ReadEnum();
              break;
            }
            case 24: {
              InactivityTicking = input.ReadBool();
              break;
            }
            case 32: {
              InactivityMsRemaining = input.ReadUInt32();
              break;
            }
            case 40: {
              InactivityAnimMsRemaining = input.ReadUInt32();
              break;
            }
          }
        }
      }
      #endif

    }

  }
  #endregion

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class CClientReconnectInfo : pb::IMessage<CClientReconnectInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CClientReconnectInfo> _parser = new pb::MessageParser<CClientReconnectInfo>(() => new CClientReconnectInfo());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CClientReconnectInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CitadelGamemessagesReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CClientReconnectInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CClientReconnectInfo(CClientReconnectInfo other) : this() {
    _hasBits0 = other._hasBits0;
    serverSteamId_ = other.serverSteamId_;
    lobbyId_ = other.lobbyId_;
    timeUpdated_ = other.timeUpdated_;
    udpConnectIp_ = other.udpConnectIp_;
    udpConnectPort_ = other.udpConnectPort_;
    compatibilityVersion_ = other.compatibilityVersion_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CClientReconnectInfo Clone() {
    return new CClientReconnectInfo(this);
  }

  /// <summary>Field number for the "server_steam_id" field.</summary>
  public const int ServerSteamIdFieldNumber = 1;
  private readonly static ulong ServerSteamIdDefaultValue = 0UL;

  private ulong serverSteamId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong ServerSteamId {
    get { if ((_hasBits0 & 1) != 0) { return serverSteamId_; } else { return ServerSteamIdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      serverSteamId_ = value;
    }
  }
  /// <summary>Gets whether the "server_steam_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasServerSteamId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "server_steam_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearServerSteamId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "lobby_id" field.</summary>
  public const int LobbyIdFieldNumber = 2;
  private readonly static ulong LobbyIdDefaultValue = 0UL;

  private ulong lobbyId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong LobbyId {
    get { if ((_hasBits0 & 2) != 0) { return lobbyId_; } else { return LobbyIdDefaultValue; } }
    set {
      _hasBits0 |= 2;
      lobbyId_ = value;
    }
  }
  /// <summary>Gets whether the "lobby_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasLobbyId {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "lobby_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearLobbyId() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "time_updated" field.</summary>
  public const int TimeUpdatedFieldNumber = 3;
  private readonly static uint TimeUpdatedDefaultValue = 0;

  private uint timeUpdated_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint TimeUpdated {
    get { if ((_hasBits0 & 4) != 0) { return timeUpdated_; } else { return TimeUpdatedDefaultValue; } }
    set {
      _hasBits0 |= 4;
      timeUpdated_ = value;
    }
  }
  /// <summary>Gets whether the "time_updated" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTimeUpdated {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "time_updated" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTimeUpdated() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "udp_connect_ip" field.</summary>
  public const int UdpConnectIpFieldNumber = 4;
  private readonly static uint UdpConnectIpDefaultValue = 0;

  private uint udpConnectIp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint UdpConnectIp {
    get { if ((_hasBits0 & 8) != 0) { return udpConnectIp_; } else { return UdpConnectIpDefaultValue; } }
    set {
      _hasBits0 |= 8;
      udpConnectIp_ = value;
    }
  }
  /// <summary>Gets whether the "udp_connect_ip" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasUdpConnectIp {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "udp_connect_ip" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearUdpConnectIp() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "udp_connect_port" field.</summary>
  public const int UdpConnectPortFieldNumber = 5;
  private readonly static uint UdpConnectPortDefaultValue = 0;

  private uint udpConnectPort_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint UdpConnectPort {
    get { if ((_hasBits0 & 16) != 0) { return udpConnectPort_; } else { return UdpConnectPortDefaultValue; } }
    set {
      _hasBits0 |= 16;
      udpConnectPort_ = value;
    }
  }
  /// <summary>Gets whether the "udp_connect_port" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasUdpConnectPort {
    get { return (_hasBits0 & 16) != 0; }
  }
  /// <summary>Clears the value of the "udp_connect_port" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearUdpConnectPort() {
    _hasBits0 &= ~16;
  }

  /// <summary>Field number for the "compatibility_version" field.</summary>
  public const int CompatibilityVersionFieldNumber = 6;
  private readonly static uint CompatibilityVersionDefaultValue = 0;

  private uint compatibilityVersion_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CompatibilityVersion {
    get { if ((_hasBits0 & 32) != 0) { return compatibilityVersion_; } else { return CompatibilityVersionDefaultValue; } }
    set {
      _hasBits0 |= 32;
      compatibilityVersion_ = value;
    }
  }
  /// <summary>Gets whether the "compatibility_version" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCompatibilityVersion {
    get { return (_hasBits0 & 32) != 0; }
  }
  /// <summary>Clears the value of the "compatibility_version" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCompatibilityVersion() {
    _hasBits0 &= ~32;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CClientReconnectInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CClientReconnectInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ServerSteamId != other.ServerSteamId) return false;
    if (LobbyId != other.LobbyId) return false;
    if (TimeUpdated != other.TimeUpdated) return false;
    if (UdpConnectIp != other.UdpConnectIp) return false;
    if (UdpConnectPort != other.UdpConnectPort) return false;
    if (CompatibilityVersion != other.CompatibilityVersion) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasServerSteamId) hash ^= ServerSteamId.GetHashCode();
    if (HasLobbyId) hash ^= LobbyId.GetHashCode();
    if (HasTimeUpdated) hash ^= TimeUpdated.GetHashCode();
    if (HasUdpConnectIp) hash ^= UdpConnectIp.GetHashCode();
    if (HasUdpConnectPort) hash ^= UdpConnectPort.GetHashCode();
    if (HasCompatibilityVersion) hash ^= CompatibilityVersion.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasServerSteamId) {
      output.WriteRawTag(9);
      output.WriteFixed64(ServerSteamId);
    }
    if (HasLobbyId) {
      output.WriteRawTag(16);
      output.WriteUInt64(LobbyId);
    }
    if (HasTimeUpdated) {
      output.WriteRawTag(24);
      output.WriteUInt32(TimeUpdated);
    }
    if (HasUdpConnectIp) {
      output.WriteRawTag(32);
      output.WriteUInt32(UdpConnectIp);
    }
    if (HasUdpConnectPort) {
      output.WriteRawTag(40);
      output.WriteUInt32(UdpConnectPort);
    }
    if (HasCompatibilityVersion) {
      output.WriteRawTag(48);
      output.WriteUInt32(CompatibilityVersion);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasServerSteamId) {
      output.WriteRawTag(9);
      output.WriteFixed64(ServerSteamId);
    }
    if (HasLobbyId) {
      output.WriteRawTag(16);
      output.WriteUInt64(LobbyId);
    }
    if (HasTimeUpdated) {
      output.WriteRawTag(24);
      output.WriteUInt32(TimeUpdated);
    }
    if (HasUdpConnectIp) {
      output.WriteRawTag(32);
      output.WriteUInt32(UdpConnectIp);
    }
    if (HasUdpConnectPort) {
      output.WriteRawTag(40);
      output.WriteUInt32(UdpConnectPort);
    }
    if (HasCompatibilityVersion) {
      output.WriteRawTag(48);
      output.WriteUInt32(CompatibilityVersion);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasServerSteamId) {
      size += 1 + 8;
    }
    if (HasLobbyId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LobbyId);
    }
    if (HasTimeUpdated) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimeUpdated);
    }
    if (HasUdpConnectIp) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UdpConnectIp);
    }
    if (HasUdpConnectPort) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UdpConnectPort);
    }
    if (HasCompatibilityVersion) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CompatibilityVersion);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CClientReconnectInfo other) {
    if (other == null) {
      return;
    }
    if (other.HasServerSteamId) {
      ServerSteamId = other.ServerSteamId;
    }
    if (other.HasLobbyId) {
      LobbyId = other.LobbyId;
    }
    if (other.HasTimeUpdated) {
      TimeUpdated = other.TimeUpdated;
    }
    if (other.HasUdpConnectIp) {
      UdpConnectIp = other.UdpConnectIp;
    }
    if (other.HasUdpConnectPort) {
      UdpConnectPort = other.UdpConnectPort;
    }
    if (other.HasCompatibilityVersion) {
      CompatibilityVersion = other.CompatibilityVersion;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          ServerSteamId = input.ReadFixed64();
          break;
        }
        case 16: {
          LobbyId = input.ReadUInt64();
          break;
        }
        case 24: {
          TimeUpdated = input.ReadUInt32();
          break;
        }
        case 32: {
          UdpConnectIp = input.ReadUInt32();
          break;
        }
        case 40: {
          UdpConnectPort = input.ReadUInt32();
          break;
        }
        case 48: {
          CompatibilityVersion = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          ServerSteamId = input.ReadFixed64();
          break;
        }
        case 16: {
          LobbyId = input.ReadUInt64();
          break;
        }
        case 24: {
          TimeUpdated = input.ReadUInt32();
          break;
        }
        case 32: {
          UdpConnectIp = input.ReadUInt32();
          break;
        }
        case 40: {
          UdpConnectPort = input.ReadUInt32();
          break;
        }
        case 48: {
          CompatibilityVersion = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class CMsgClientAccountSyncStorageFile : pb::IMessage<CMsgClientAccountSyncStorageFile>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CMsgClientAccountSyncStorageFile> _parser = new pb::MessageParser<CMsgClientAccountSyncStorageFile>(() => new CMsgClientAccountSyncStorageFile());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CMsgClientAccountSyncStorageFile> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CitadelGamemessagesReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientAccountSyncStorageFile() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientAccountSyncStorageFile(CMsgClientAccountSyncStorageFile other) : this() {
    _hasBits0 = other._hasBits0;
    version_ = other.version_;
    ids_ = other.ids_.Clone();
    values_ = other.values_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CMsgClientAccountSyncStorageFile Clone() {
    return new CMsgClientAccountSyncStorageFile(this);
  }

  /// <summary>Field number for the "version" field.</summary>
  public const int VersionFieldNumber = 1;
  private readonly static uint VersionDefaultValue = 0;

  private uint version_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Version {
    get { if ((_hasBits0 & 1) != 0) { return version_; } else { return VersionDefaultValue; } }
    set {
      _hasBits0 |= 1;
      version_ = value;
    }
  }
  /// <summary>Gets whether the "version" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasVersion {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "version" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearVersion() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "ids" field.</summary>
  public const int IdsFieldNumber = 2;
  private static readonly pb::FieldCodec<uint> _repeated_ids_codec
      = pb::FieldCodec.ForUInt32(16);
  private readonly pbc::RepeatedField<uint> ids_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> Ids {
    get { return ids_; }
  }

  /// <summary>Field number for the "values" field.</summary>
  public const int ValuesFieldNumber = 3;
  private static readonly pb::FieldCodec<uint> _repeated_values_codec
      = pb::FieldCodec.ForUInt32(24);
  private readonly pbc::RepeatedField<uint> values_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> Values {
    get { return values_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CMsgClientAccountSyncStorageFile);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CMsgClientAccountSyncStorageFile other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Version != other.Version) return false;
    if(!ids_.Equals(other.ids_)) return false;
    if(!values_.Equals(other.values_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasVersion) hash ^= Version.GetHashCode();
    hash ^= ids_.GetHashCode();
    hash ^= values_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasVersion) {
      output.WriteRawTag(8);
      output.WriteUInt32(Version);
    }
    ids_.WriteTo(output, _repeated_ids_codec);
    values_.WriteTo(output, _repeated_values_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasVersion) {
      output.WriteRawTag(8);
      output.WriteUInt32(Version);
    }
    ids_.WriteTo(ref output, _repeated_ids_codec);
    values_.WriteTo(ref output, _repeated_values_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasVersion) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Version);
    }
    size += ids_.CalculateSize(_repeated_ids_codec);
    size += values_.CalculateSize(_repeated_values_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CMsgClientAccountSyncStorageFile other) {
    if (other == null) {
      return;
    }
    if (other.HasVersion) {
      Version = other.Version;
    }
    ids_.Add(other.ids_);
    values_.Add(other.values_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Version = input.ReadUInt32();
          break;
        }
        case 18:
        case 16: {
          ids_.AddEntriesFrom(input, _repeated_ids_codec);
          break;
        }
        case 26:
        case 24: {
          values_.AddEntriesFrom(input, _repeated_values_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Version = input.ReadUInt32();
          break;
        }
        case 18:
        case 16: {
          ids_.AddEntriesFrom(ref input, _repeated_ids_codec);
          break;
        }
        case 26:
        case 24: {
          values_.AddEntriesFrom(ref input, _repeated_values_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
