// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: steammessages_unified_base.steamworkssdk.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from steammessages_unified_base.steamworkssdk.proto</summary>
public static partial class SteammessagesUnifiedBaseSteamworkssdkReflection {

  #region Descriptor
  /// <summary>File descriptor for steammessages_unified_base.steamworkssdk.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SteammessagesUnifiedBaseSteamworkssdkReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ci5zdGVhbW1lc3NhZ2VzX3VuaWZpZWRfYmFzZS5zdGVhbXdvcmtzc2RrLnBy",
          "b3RvGiBnb29nbGUvcHJvdG9idWYvZGVzY3JpcHRvci5wcm90bypdChNFUHJv",
          "dG9FeGVjdXRpb25TaXRlEiAKHGtfRVByb3RvRXhlY3V0aW9uU2l0ZVVua25v",
          "d24QABIkCiBrX0VQcm90b0V4ZWN1dGlvblNpdGVTdGVhbUNsaWVudBADOjQK",
          "C2Rlc2NyaXB0aW9uEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjQ",
          "hgMgASgJOj4KE3NlcnZpY2VfZGVzY3JpcHRpb24SHy5nb29nbGUucHJvdG9i",
          "dWYuU2VydmljZU9wdGlvbnMY0IYDIAEoCTp1ChZzZXJ2aWNlX2V4ZWN1dGlv",
          "bl9zaXRlEh8uZ29vZ2xlLnByb3RvYnVmLlNlcnZpY2VPcHRpb25zGNiGAyAB",
          "KA4yFC5FUHJvdG9FeGVjdXRpb25TaXRlOhxrX0VQcm90b0V4ZWN1dGlvblNp",
          "dGVVbmtub3duOjwKEm1ldGhvZF9kZXNjcmlwdGlvbhIeLmdvb2dsZS5wcm90",
          "b2J1Zi5NZXRob2RPcHRpb25zGNCGAyABKAk6OAoQZW51bV9kZXNjcmlwdGlv",
          "bhIcLmdvb2dsZS5wcm90b2J1Zi5FbnVtT3B0aW9ucxjQhgMgASgJOkMKFmVu",
          "dW1fdmFsdWVfZGVzY3JpcHRpb24SIS5nb29nbGUucHJvdG9idWYuRW51bVZh",
          "bHVlT3B0aW9ucxjQhgMgASgJQgVIAYABAA=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EProtoExecutionSite), }, new pb::Extension[] { SteammessagesUnifiedBaseSteamworkssdkExtensions.Description, SteammessagesUnifiedBaseSteamworkssdkExtensions.ServiceDescription, SteammessagesUnifiedBaseSteamworkssdkExtensions.ServiceExecutionSite, SteammessagesUnifiedBaseSteamworkssdkExtensions.MethodDescription, SteammessagesUnifiedBaseSteamworkssdkExtensions.EnumDescription, SteammessagesUnifiedBaseSteamworkssdkExtensions.EnumValueDescription }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of steammessages_unified_base.steamworkssdk.proto</summary>
public static partial class SteammessagesUnifiedBaseSteamworkssdkExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> Description =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, string> ServiceDescription =
    new pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, global::EProtoExecutionSite> ServiceExecutionSite =
    new pb::Extension<global::Google.Protobuf.Reflection.ServiceOptions, global::EProtoExecutionSite>(50008, pb::FieldCodec.ForEnum(400064, x => (int) x, x => (global::EProtoExecutionSite) x, global::EProtoExecutionSite.KEprotoExecutionSiteUnknown));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, string> MethodDescription =
    new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.EnumOptions, string> EnumDescription =
    new pb::Extension<global::Google.Protobuf.Reflection.EnumOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string> EnumValueDescription =
    new pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
}

#region Enums
public enum EProtoExecutionSite {
  [pbr::OriginalName("k_EProtoExecutionSiteUnknown")] KEprotoExecutionSiteUnknown = 0,
  [pbr::OriginalName("k_EProtoExecutionSiteSteamClient")] KEprotoExecutionSiteSteamClient = 3,
}

#endregion


#endregion Designer generated code
