// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: valveextensions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from valveextensions.proto</summary>
public static partial class ValveextensionsReflection {

  #region Descriptor
  /// <summary>File descriptor for valveextensions.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ValveextensionsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChV2YWx2ZWV4dGVuc2lvbnMucHJvdG8aIGdvb2dsZS9wcm90b2J1Zi9kZXNj",
          "cmlwdG9yLnByb3RvOj8KD3ZhbHZlX21hcF9maWVsZBIdLmdvb2dsZS5wcm90",
          "b2J1Zi5GaWVsZE9wdGlvbnMYyNwDIAEoCDoFZmFsc2U6PQoNdmFsdmVfbWFw",
          "X2tleRIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYydwDIAEoCDoF",
          "ZmFsc2U6PQoRZGlmZl9lbmNvZGVfZmllbGQSHS5nb29nbGUucHJvdG9idWYu",
          "RmllbGRPcHRpb25zGMrcAyABKAU6ATA6PAoMZGVsdGFfaWdub3JlEh0uZ29v",
          "Z2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjL3AMgASgIOgVmYWxzZTo/ChNz",
          "dGVhbW1sX21heF9lbnRyaWVzEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0",
          "aW9ucxjM3AMgASgNOgEwOkQKFHN0ZWFtbWxfaXNfdGltZXN0YW1wEh0uZ29v",
          "Z2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjN3AMgASgIOgVmYWxzZTo8ChBz",
          "dGVhbWxlYXJuX2NvdW50Eh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9u",
          "cxjO3AMgASgNOgEwOkAKFHNjaGVtYV9mcmllbmRseV9uYW1lEiEuZ29vZ2xl",
          "LnByb3RvYnVmLkVudW1WYWx1ZU9wdGlvbnMY6AcgASgJOj4KEnNjaGVtYV9k",
          "ZXNjcmlwdGlvbhIhLmdvb2dsZS5wcm90b2J1Zi5FbnVtVmFsdWVPcHRpb25z",
          "GOkHIAEoCTpGChpzY2hlbWFfc3VwcHJlc3NfZW51bWVyYXRvchIhLmdvb2ds",
          "ZS5wcm90b2J1Zi5FbnVtVmFsdWVPcHRpb25zGOoHIAEoCA=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { ValveextensionsExtensions.ValveMapField, ValveextensionsExtensions.ValveMapKey, ValveextensionsExtensions.DiffEncodeField, ValveextensionsExtensions.DeltaIgnore, ValveextensionsExtensions.SteammlMaxEntries, ValveextensionsExtensions.SteammlIsTimestamp, ValveextensionsExtensions.SteamlearnCount, ValveextensionsExtensions.SchemaFriendlyName, ValveextensionsExtensions.SchemaDescription, ValveextensionsExtensions.SchemaSuppressEnumerator }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of valveextensions.proto</summary>
public static partial class ValveextensionsExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> ValveMapField =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(61000, pb::FieldCodec.ForBool(488000, false));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> ValveMapKey =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(61001, pb::FieldCodec.ForBool(488008, false));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int> DiffEncodeField =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, int>(61002, pb::FieldCodec.ForInt32(488016, 0));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> DeltaIgnore =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(61003, pb::FieldCodec.ForBool(488024, false));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, uint> SteammlMaxEntries =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, uint>(61004, pb::FieldCodec.ForUInt32(488032, 0));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> SteammlIsTimestamp =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(61005, pb::FieldCodec.ForBool(488040, false));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, uint> SteamlearnCount =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, uint>(61006, pb::FieldCodec.ForUInt32(488048, 0));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string> SchemaFriendlyName =
    new pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string>(1000, pb::FieldCodec.ForString(8002, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string> SchemaDescription =
    new pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, string>(1001, pb::FieldCodec.ForString(8010, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, bool> SchemaSuppressEnumerator =
    new pb::Extension<global::Google.Protobuf.Reflection.EnumValueOptions, bool>(1002, pb::FieldCodec.ForBool(8016, false));
}


#endregion Designer generated code
